[package]
name = "logging"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["registry", "std", "fmt", "ansi"] }
anyhow = { version = "1.0.100", default-features = false }