[package]
name = "signal"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = { version = "2.5.0", default-features = false }
tracing = { version = "0", default-features = false }
tokio = { version = "1", features = ["signal", "macros"], default-features = false }
